### ISSUE TITLE
Testing with Jest fails

### ISSUE THREAD

**Issue by ackushiw-rialtic** [frankleng/cloudflare-cognito-jwt-verifier#2]
Using Hono's starter template https://honojs.dev/docs/getting-started/cloudflare-workers/ running a test fails with the following message:

**Jest encountered an unexpected token**
```bash
Details:

<PROJECT_ROOT>/node_modules/.pnpm/jose@4.8.1/node_modules/jose/dist/browser/index.js:1
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){export { compactDecrypt } from './jwe/compact/decrypt.js';
                                                                                  ^^^^^^

SyntaxError: Unexpected token 'export'

      at Runtime.createScriptFromCode (../../node_modules/.pnpm/jest-runtime@28.1.3/node_modules/jest-runtime/build/index.js:1796:14)
      at Object.<anonymous> (../../node_modules/.pnpm/cloudflare-cognito-jwt-verifier@1.1.3/node_modules/cloudflare-cognito-jwt-verifier/src/index.ts:1:1)

**Comment by frankleng** [comment]
@ackushiw-rialtic seems like it's importing `.ts` without compiling. are you using ts-jest?
if u make a repo to reproduce this i'll take a look.

PSA - I no longer use Cognito. it's buggy.

**Comment by ackushiw-rialtic** [comment]
I tried it with ts-jest and without. I'll do some further research. Out of curiosity what were the bugs you found in Cognito and what are you using now?

**Comment by frankleng** [comment]
> I tried it with ts-jest and without. I'll do some further research. Out of curiosity what were the bugs you found in Cognito and what are you using now?

there were many. what broke the camels back was https://github.com/aws-amplify/amplify-flutter/issues/1716
(not specific to amplify-flutter, but Cognito itself) 
it's a 5+ yr bug that forces the user to oauth twice during signup.
we now use Firebase auth (it's even free...), and u can use https://github.com/frankleng/cloudflare-firebase-jwt-verifier for cf
